### ISSUE TITLE
Line 163 in `lacam.py`

### ISSUE THREAD

**Issue by Arseni1919** [Kei18/py-lacam#5]
Lines 157-167 in `lacam.py` file:
```python
# new configuration
N_new = HighLevelNode(
    Q=Q_to,
    parent=N,
    order=self.get_order(Q_to),
    g=N.g + self.get_edge_cost(N.Q, Q_to),
    h=self.get_h_value(Q_init),
)
```

Is it supposed to be: `h=self.get_h_value(Q_to),`, no?..
If not, why is it important to put `Q_init` inside?
Thank you in advance,
Arseni

**Comment by Kei18** [comment]
Yes, it should be `Q_to`; otherwise, the optimality disappears. Thanks!
