### ISSUE TITLE
Edge collision check in PIBT inside LaCAM(*) implementation

### ISSUE THREAD

**Issue by Arseni1919** [Kei18/py-lacam#8]
The journal version of PIBT pseudocode is:

![pibt_journal](https://github.com/Kei18/py-lacam/assets/55444116/fa37f11a-6d22-48f4-a6a9-8ac01aa1c5f0)

I want to check a little issue with the code regarding edge collision (ec) checks.
While in pure PIBT algorithm, the pseudocode totally works, in LaCAM implementation PIBT function receives some predecided locations for several agents due to `LowLevelNode`'s constraints.
In the latter case, unfortunately, the previous ec check will not catch all the cases, where the ec may occur not only with the agent j.

```python
if agent_j is not None and config_from[agent_j.name] == nei_node:
    continue
```

May I suggest the following code for completeness:

```python
def there_is_ec(
        agent_i: AgentAlg,
        nei_node: Node,
        config_from: Dict[str, Node],
        config_to: Dict[str, Node],
) -> bool:
    node_from = config_from[agent_i.name]
    for other_name, other_f_node in config_from.items():
        if other_name == agent_i.name:
            continue
        if other_name not in config_to:
            continue
        other_t_node = config_to[other_name]
        if other_f_node == nei_node and other_t_node == node_from:
            return True
    return False
```

Am I missing any details about the ec check?...

Thank you!

**Comment by Kei18** [comment]
I do not see issues with the implementation of the edge collision check. This part should (efficiently) catch all cases, regardless of the work of the low-level node.
https://github.com/Kei18/py-lacam/blob/pibt/pycam/pibt.py#L42-L46

Let me know if you have counterexamples.

**Comment by Arseni1919** [comment]
Great! That code solves the problem completely indeed:
```python
j = self.occupied_now[v]

# avoid edge collision
if j != self.NIL and Q_to[j] == Q_from[i]:
    continue
```
( https://github.com/Kei18/py-lacam/blob/pibt/pycam/pibt.py#L42-L46 )

The difference is what does the agent **j** mean in each case:
- in pseudocode (presented above), the j agent is one that comes with the input of the function
- in the snippet the j agent is one that occupies the vertex (`occupied_now[v]`)

IMO, that might confuse a bit, that's all.
Hope I was clear with the description.

**Comment by Kei18** [comment]
Right, in recent implementations of PIBT I do not use arguments for agent-j. I realised it was redundant from an implementation perspective.
